
version: '3.4'

services:
  cbntl/my-simple-node-app:
    image: cbntl/my-simple-node-app	
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - "8080:80"
    healthcheck:
      test: curl --fail http://localhost:3000/ || exit 1
      interval: 60s
      retries: 3
      start_period: 20s
      timeout: 10s